name: Test Project
on: push
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run test
        run: |
          cd 2nd
          cd 02\ Starting\ Project 
          yarn test
  
